package com.troonvinyl.iphoneshare;

import android.app.*;import android.os.*;import android.graphics.BitmapFactory;import android.graphics.Bitmap;import android.net.wifi.WifiManager;import android.text.format.Formatter;import android.view.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity{
 ImageView image; WebView web; LinearLayout info; TextView address; final ArrayList<File> files=new ArrayList<>(); int index=-1; HttpServer server; ExecutorService pool=Executors.newCachedThreadPool();
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);setContentView(R.layout.activity_main);image=findViewById(R.id.image);web=findViewById(R.id.web);info=findViewById(R.id.info);address=findViewById(R.id.address);web.getSettings().setJavaScriptEnabled(true);web.setWebViewClient(new WebViewClient());String ip=getIp();address.setText("Open http://"+ip+":8080 on your iPhone");server=new HttpServer(8080);pool.execute(server);}
 String getIp(){try{WifiManager w=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);return Formatter.formatIpAddress(w.getConnectionInfo().getIpAddress());}catch(Exception e){return "TV-IP";}}
 void showFile(File f){runOnUiThread(()->{web.setVisibility(View.GONE);image.setVisibility(View.VISIBLE);info.setVisibility(View.GONE);Bitmap bm=BitmapFactory.decodeFile(f.getAbsolutePath());image.setImageBitmap(bm);});}
 void showUrl(String u){runOnUiThread(()->{image.setVisibility(View.GONE);info.setVisibility(View.GONE);web.setVisibility(View.VISIBLE);web.loadUrl(u);});}
 void next(int d){if(files.isEmpty())return;index=(index+d+files.size())%files.size();showFile(files.get(index));}
 void clear(){for(File f:files)f.delete();files.clear();index=-1;runOnUiThread(()->{image.setImageDrawable(null);web.setVisibility(View.GONE);info.setVisibility(View.VISIBLE);});}
 @Override public boolean onKeyDown(int key,KeyEvent e){if(key==KeyEvent.KEYCODE_DPAD_RIGHT){next(1);return true;}if(key==KeyEvent.KEYCODE_DPAD_LEFT){next(-1);return true;}return super.onKeyDown(key,e);}
 class HttpServer implements Runnable{ServerSocket ss;int port;HttpServer(int p){port=p;}public void run(){try{ss=new ServerSocket(port);while(true){Socket s=ss.accept();pool.execute(()->handle(s));}}catch(Exception ignored){}}void send(OutputStream o,String status,String type,byte[] body)throws Exception{String h="HTTP/1.1 "+status+"\r\nContent-Type: "+type+"\r\nAccess-Control-Allow-Origin: *\r\nContent-Length: "+body.length+"\r\nConnection: close\r\n\r\n";o.write(h.getBytes("UTF-8"));o.write(body);o.flush();}
 void handle(Socket s){try{BufferedInputStream in=new BufferedInputStream(s.getInputStream());String line=readLine(in);if(line==null){s.close();return;}String[] p=line.split(" ");String method=p[0],path=p[1];int len=0;String ct="";while(!(line=readLine(in)).isEmpty()){String low=line.toLowerCase();if(low.startsWith("content-length:"))len=Integer.parseInt(line.substring(15).trim());if(low.startsWith("content-type:"))ct=line.substring(13).trim();}byte[] body=new byte[len];int n=0;while(n<len){int r=in.read(body,n,len-n);if(r<0)break;n+=r;}OutputStream out=s.getOutputStream();if(method.equals("OPTIONS")){send(out,"204 No Content","text/plain",new byte[0]);s.close();return;}if(method.equals("GET")&&path.equals("/")){send(out,"200 OK","text/html; charset=utf-8",html().getBytes("UTF-8"));}else if(method.equals("POST")&&path.startsWith("/upload")){String name="image";int q=path.indexOf("name=");if(q>=0)name=URLDecoder.decode(path.substring(q+5),"UTF-8");File f=new File(getCacheDir(),System.currentTimeMillis()+"_"+safe(name));try(FileOutputStream fos=new FileOutputStream(f)){fos.write(body);}files.add(f);index=files.size()-1;showFile(f);send(out,"200 OK","text/plain","OK".getBytes("UTF-8"));}else if(method.equals("POST")&&path.equals("/next")){next(1);send(out,"200 OK","text/plain","OK".getBytes());}else if(method.equals("POST")&&path.equals("/prev")){next(-1);send(out,"200 OK","text/plain","OK".getBytes());}else if(method.equals("POST")&&path.equals("/clear")){clear();send(out,"200 OK","text/plain","OK".getBytes());}else if(method.equals("POST")&&path.equals("/url")){showUrl(new String(body,"UTF-8").trim());send(out,"200 OK","text/plain","OK".getBytes());}else send(out,"404 Not Found","text/plain","Not found".getBytes());s.close();}catch(Exception ignored){try{s.close();}catch(Exception e){}}}
 String readLine(InputStream in)throws Exception{StringBuilder b=new StringBuilder();int c;while((c=in.read())!=-1){if(c=='\n')break;if(c!='\r')b.append((char)c);}return b.toString();}String safe(String s){return s.replaceAll("[^A-Za-z0-9._-]","_");}
 String html(){return "<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><title>iPhone Share TV</title><style>body{font-family:system-ui;background:#0b0d12;color:white;padding:20px;max-width:700px;margin:auto}button,input{font:inherit;padding:14px;margin:6px 0;width:100%;border-radius:12px;border:0}button{font-weight:700}</style><h1>📺 iPhone Share</h1><p>Select photos/screenshots and send them directly to this TV.</p><input id='f' type='file' accept='image/*' multiple><button onclick='send()'>Send to TV</button><input id='u' placeholder='https://example.com'><button onclick='url()'>Show web page</button><button onclick=fetch('/prev',{method:'POST'})>Previous</button><button onclick=fetch('/next',{method:'POST'})>Next</button><button onclick=fetch('/clear',{method:'POST'})>Clear</button><script>async function send(){for(const f of f.files)await fetch('/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':f.type},body:f})}async function url(){await fetch('/url',{method:'POST',headers:{'Content-Type':'text/plain'},body:u.value})}</script>";}
 }
}
